# action.yml
name: 'iamdevops995-docker-action-for-vpc-peering'
description: 'iamdevops995-docker-action-for-vpc-peering'
inputs:
  # github_token:  # id of input
  #   description: 'provide github_token'
  #   required: true
  ec2-name:
    description: "Provide ec2 name"
    required: true
  ssh-key:
    description: "Provide ssh key"
    required: true
  public-ip-ec2:
    description: "Provide pulic ip of ec2"
    required: true
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ec2-name }}
    - ${{ inputs.ssh-key }}
    - ${{ inputs.public-ip-ec2 }}
branding:
  icon: 'award'
  color: 'green'
