name: aws vpc peering using terraform
permissions:
  id-token: write
  contents: read
  pull-requests: write
on:
  pull_request_target:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:
  # pull_request: 
  #   types:
  #     - opened
  #   branches:
  #     - 'main'
env:
  tf_actions_working_dir: ./terraform
defaults:
  run:
    shell: bash
    working-directory: ./terraform
jobs:
  terraform-setup:
    name: Terraform setup
    runs-on: ubuntu-24.04
    environment:
      name: production
    steps:
      - name: checkout reposistory
        uses: actions/checkout@v5
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
      - name: check terraform cli version
        run: terraform --version
      - name: Cache Terraform
        uses: actions/cache@v4
        with:
          path: |
            .terraform
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-
      - name: aws-configure
        uses: ./.github/actions/oidc-aws/
        with:
          role-to-assume: arn:aws:iam::277968024163:role/vpcPeeringRole
          aws-region: us-east-1
      - name: Terraform format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Init
        id: init
        run: terraform init -input=false
      - name: Terraform validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan 
        id: plan
        run: terraform plan -no-color -input=false  | tee plan.txt
        continue-on-error: true
      - name: Terraform Apply
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve
      - name: Get EC2 IP addresses
        id: ec2
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=test-1a" \
            --query "Reservations[].Instances[].PublicIpAddress" \
            --output text)

          PRIVATE_IP=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=test-2b" \
            --query "Reservations[].Instances[].PrivateIpAddress" \
            --output text)

          echo "public_ip_address=$PUBLIC_IP" >> $GITHUB_OUTPUT
          echo "private_ip_address=$PRIVATE_IP" >> $GITHUB_OUTPUT
      - name: ssh into the ec2 instance test-1a and ping test-2b private ip address
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ steps.ec2.outputs.public_ip_address }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            touch ping_result.txt
            # ls -lrt
            # pwd
            echo "##############################" > ping_result.txt
            echo "Ping Test from test-1a to test-2b" >> ping_result.txt
            echo "##############################" >> ping_result.txt 
            echo HOSTNAME: ${{ steps.ec2.outputs.public_ip_address }} >> ping_result.txt
            uptime  >> ping_result.txt
            date >> ping_result.txt
            echo "###############################" >> ping_result.txt
            echo "Pinging to private IP Address: ${{ steps.ec2.outputs.private_ip_address }}" >> ping_result.txt
            ping -c 4 ${{ steps.ec2.outputs.private_ip_address }} >> ping_result.txt
            if [ $? -eq 0 ]; then
              echo "✅ Successfully executed commands to all host."
            else
              echo "❌ Failed to execute commands to some host."
            fi
      - name: Copy ping result from EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > pri_key
          chmod 600 pri_key
          scp -o StrictHostKeyChecking=no \
            -i pri_key \
            ubuntu@${{ steps.ec2.outputs.public_ip_address }}:/home/ubuntu/ping_result.txt  $GITHUB_WORKSPACE/terraform/ping_result.txt
      - name: Display ping result
        run: |
          cat ping_result.txt
      # - name: upload ping result as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ping-result
      #     path: $GITHUB_WORKSPACE/terraform/ping_result.txt
          # retention-days: 1
      - uses: actions/github-script@v7
        if:  github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
            })

            // 2. Prepare format of the comment
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            // 3. If we have a comment, update it, otherwise create a new one
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }


